### PR TITLE
Update AscmvcEventManager.php

### PR DESCRIPTION
**Pull request by manzwebdesigns**
This fix lets it work on Windows.

### CODE REVIEW

**Comment by andrewscaya** [comment]
Many thanks, @manzwebdesigns! I'll be adding a corresponding unit test.

**Comment by manzwebdesigns** [comment]
You are very welcome!

**Comment by andrewscaya** [comment]
@manzwebdesigns The unit test has been added. You can now test branch 2.0.1-dev on Windows to make sure that everything is working fine.

**Comment by andrewscaya** [comment]
Included in release 2.0.1.

**Comment by manzwebdesigns** [comment]
Awesome!

**Pull request merged**
